version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    networks:
      - self-heal-net

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
    networks:
      - self-heal-net

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/config.yml:/etc/alertmanager/config.yml:ro
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    networks:
      - self-heal-net

  blackbox:
    image: prom/blackbox-exporter:latest
    container_name: blackbox
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox:/etc/blackbox_exporter:ro
    command:
      - '--config.file=/etc/blackbox_exporter/config.yml'
    networks:
      - self-heal-net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - self-heal-net
    # keep restart policy so it will be restarted by docker if crashed
    restart: unless-stopped

  ansible-handler:
    build: ./ansible-handler
    container_name: ansible-handler
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock                       # allow control of docker
    ports:
      - "5001:5001"
    networks:
      - self-heal-net

networks:
  self-heal-net:
    driver: bridge
