groups:
  - name: nginx-alerts
    rules:
      - alert: NginxDown
        expr: up{job="nginx"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "NGINX is down"
          description: "The NGINX service is not reachable for more than 30s."
