---
- name: Restart nginx docker container (self-healing playbook)
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Ensure community.docker is available (best-effort)
      ansible.builtin.command: ansible-galaxy collection install community.docker
      ignore_errors: yes

    - name: Try to start existing nginx_service container
      community.docker.docker_container:
        name: nginx_service
        state: started
      ignore_errors: yes

    - name: Fallback - start container with docker run if it does not exist
      ansible.builtin.command: docker run -d --name nginx_service -p 8080:80 nginx:stable
      when: "'nginx_service' not in lookup('ansible.builtin.pipe', 'docker ps -a --format \"{{.Names}}\"')"
      ignore_errors: yes
